// src/app/terms/page.tsx
// Terms & Conditions page for PropSignal (Australia-only)
// This is a server component. No client code needed.

import React from "react";
import { Header } from "@/app/components/header"
import { Footer } from "@/app/components/footer"

export const metadata = {
  title: "Terms & Conditions – PropSignal",
  description:
    "PropSignal Terms & Conditions for the use of our Australian real-estate insights platform.",
};

export default function TermsPage() {


  return (
    <div className="min-h-screen bg-transparent">
          <Header />
    <main
      className="
        prose prose-slate prose-lg
        max-w-3xl mx-auto px-4 py-8
        bg-transparent
        prose-headings:text-gray-900
        prose-p:text-gray-700
        prose-strong:text-gray-800
        prose-a:text-blue-600 hover:prose-a:underline
      "
    >
      <h1>Terms &amp; Conditions</h1>

      <p className="italic text-gray-600">
        These Terms &amp; Conditions (“Terms”) govern your access to and use of
        the PropSignal website and Services. By accessing or using our site, you
        agree to be bound by these Terms.
      </p>

      <h2>1. About PropSignal</h2>
      <p>
        PropSignal (“we”, “us”, or “our”) operates an online platform providing
        data-driven property insights and AI-assisted analysis for the Australian
        residential real-estate market. The Services are designed primarily for
        users located within Australia.
      </p>

      <h2>2. Acceptance of Terms</h2>
      <p>
        By accessing or using PropSignal, you acknowledge that you have read,
        understood, and agree to be bound by these Terms. If you do not agree,
        you must not use this website or any of our Services.
      </p>

      <h2>3. Use of Services</h2>
      <p>
        PropSignal provides information and AI-generated insights for general
        research and analytical purposes only. You agree to use the Services in
        accordance with applicable Australian laws and solely for lawful personal
        or internal business purposes.
      </p>
      <ul>
        <li>
          You must not use PropSignal to post, upload, or transmit any material
          that is unlawful, defamatory, or infringes intellectual property rights.
        </li>
        <li>
          You must not attempt to scrape, reproduce, resell, or redistribute any
          part of the Service or its content.
        </li>
        <li>
          You must not input sensitive, confidential, or personally identifiable
          information into the AI chat or any form fields.
        </li>
      </ul>

<h2>4. User Responsibilities</h2>
<p>
  By accessing or using PropSignal, you agree to use the website and its
  Services in a lawful, responsible, and respectful manner. You are solely
  responsible for ensuring that your use of the site complies with all
  applicable Australian laws and regulations.
</p>

<p>
  In particular, you agree that you will not:
</p>

<ul>
  <li>
    Use the website or any of its AI-generated outputs for unlawful, misleading,
    defamatory, or fraudulent purposes.
  </li>
  <li>
    Submit, transmit, or share any material that contains personal, confidential,
    or sensitive information — including financial details, identification
    numbers, or private addresses — through any part of the platform.
  </li>
  <li>
    Reverse engineer, reproduce, or otherwise attempt to extract or repurpose
    the underlying data, models, or algorithms that power the PropSignal Service.
  </li>
  <li>
    Scrape, mine, or harvest any information from the site or interfere with its
    normal operation using automated tools, bots, or scripts.
  </li>
  <li>
    Misrepresent your identity or affiliation, or use the Services in a way that
    could harm PropSignal’s reputation or other users.
  </li>
  <li>
    Attempt to circumvent any technical, security, or access controls implemented
    on the platform.
  </li>
</ul>

<p>
  PropSignal reserves the right to restrict or terminate access to the website or
  Services at any time, without notice, if any conduct is found to violate these
  Terms or is otherwise deemed harmful to the operation or integrity of the
  platform.
</p>


      <h2>5. Use of AI-Generated Insights</h2>
      <div className="p-4 my-4 bg-yellow-50 border-l-4 border-yellow-400">
        <p className="font-semibold">Important:</p>
        <p>
          The insights and outputs generated by PropSignal’s AI systems are
          derived from publicly available Australian data sources. While we make
          reasonable efforts to ensure accuracy, such outputs may contain
          approximations or errors. The information provided does not constitute
          professional, financial, investment, or legal advice.
        </p>
      </div>
      <p>
        Users should independently verify all property data, insights, and
        recommendations before relying on them. PropSignal accepts no
        responsibility for decisions made based on AI-generated outputs.
      </p>

      <h2>6. Third-Party Data and Attribution</h2>
      <p>
        All property and suburb information displayed on PropSignal is derived
        from <strong>publicly available Australian datasets</strong> under
        free-use or open-data licences. We acknowledge the respective rights of
        data custodians and third parties that provide open-access information.
      </p>

      <h2>7. Intellectual Property</h2>
      <p>
        All trademarks, logos, graphics, text, and design elements displayed on
        this website are owned or licensed by PropSignal, except where otherwise
        noted. You may not copy, reproduce, modify, or distribute any part of
        the site without prior written consent.
      </p>

      <h2>8. Disclaimer</h2>
      <p>
        PropSignal provides its Services on an “as is” and “as available” basis.
        We make no representations or warranties of any kind, express or implied,
        regarding the accuracy, completeness, reliability, or availability of the
        content or Services.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, PropSignal, its owners, affiliates,
        or contributors are not liable for any loss, damage, cost, or expense,
        whether direct, indirect, incidental, consequential, or otherwise,
        arising out of or in connection with your use of the Services or reliance
        on any content or insights generated on this site.
      </p>

      <h2>10. Service Modifications and Availability</h2>
      <p>
        We may update, modify, suspend, or discontinue any part of the website or
        Services at any time without prior notice. We are not liable for any
        downtime or interruption in access.
      </p>

      <h2>11. Third-Party Links</h2>
      <p>
        The PropSignal website may include links to external websites or resources.
        We are not responsible for the content, policies, or practices of those
        third-party sites. Access to such sites is at your own risk.
      </p>

      <h2>12. Privacy</h2>
      <p>
        Your use of the website is also governed by our{" "}
        <a href="/privacy-policy">Privacy Policy</a>, which explains how we
        collect, use, and protect personal information.
      </p>

      <h2>13. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the Commonwealth of Australia and
        the State of Victoria. Any disputes arising in connection with these Terms
        will be subject to the exclusive jurisdiction of the courts of Victoria,
        Australia.
      </p>

      <h2>14. Contact</h2>
      <p>
        For any questions regarding these Terms, please use the{" "}
        <strong>Submit Feedback</strong> form available at the top of this page.
      </p>

    </main>
    <Footer />
          </div>
  );
}
